COUNTRIES = [
    "India",
    "Unknown",
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua & Deps",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cape Verde",
    "Central African Rep",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo",
    "Congo {Democratic Rep}",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "East Timor",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland {Republic}",
    "Israel",
    "Italy",
    "Ivory Coast",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Korea North",
    "Korea South",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macedonia",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar, {Burma}",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russian Federation",
    "Rwanda",
    "St Kitts & Nevis",
    "St Lucia",
    "Saint Vincent & the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome & Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Swaziland",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Togo",
    "Tonga",
    "Trinidad & Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe",
]

STATES = (
    ("Andaman and Nicobar Islands", "Andaman and Nicobar Islands"),
    ("Andhra Pradesh", "Andhra Pradesh"),
    ("Assam", "Assam"),
    ("Bihar", "Bihar"),
    ("Chandigarh", "Chandigarh"),
    ("Chattisgarh", "Chattisgarh"),
    ("Dadar and Nagar Haveli", "Dadar and Nagar Haveli"),
    ("Daman and Diu", "Daman and Diu"),
    ("Delhi", "Delhi"),
    ("Goa", "Goa"),
    ("Gujarat", "Gujarat"),
    ("Haryana", "Haryana"),
    ("Himachal Pradesh", "Himachal Pradesh"),
    ("Jammu and Kashmir", "Jammu and Kashmir"),
    ("Jharkhand", "Jharkand"),
    ("Karnataka", "Karnataka"),
    ("Kerala", "Kerala"),
    ("Ladakh", "Ladakh"),
    ("Lakshadweep", "Lakshadweep"),
    ("Madhya Pradesh", "Madhya Pradesh"),
    ("Maharashtra", "Maharashtra"),
    ("Manipur", "Manipur"),
    ("Meghalaya", "Meghalaya"),
    ("Mizoram", "Mizoram"),
    ("Nagaland", "Nagaland"),
    ("Delhi", "Delhi"),
    ("Odisha", "Odisha"),
    ("Puducherry", "Puducherry"),
    ("Punjab", "Punjab"),
    ("Rajasthan", "Rajasthan"),
    ("Sikkim", "Sikkim"),
    ("Tamil Nadu", "Tamil Nadu"),
    ("Telangana", "Telangana"),
    ("Tripura", "Tripura"),
    ("Uttar Pradesh", "Uttar Pradesh"),
    ("Uttarakhand", "Uttarakhand"),
    ("West Bengal", "West Bengal"),
)

STATE_WISE_DISTRICTS = {'telangana': ['Narayanpet', 'Jayashankar', 'Bhadradri Kothagudem', 'Yadadri Bhuvanagiri', 'Warangal Urban', 'Warangal Rural', 'Wanaparthy', 'Vikarabad', 'Suryapet', 'Siddipet', 'Sangareddy', 'Ranga Reddy', 'Rajanna Sircilla', 'Peddapalli', 'Nizamabad', 'Nirmal', 'Nalgonda', 'Nagarkurnool', 'Medchal Malkajgiri', 'Medak', 'Mancherial', 'Mahabubnagar', 'Mahabubabad', 'Kumuram Bheem Asifabad', 'Khammam', 'Karimnagar', 'Kamareddy', 'Jogulamba Gadwal', 'Mulugu', 'Jangoan', 'Jagitial', 'Hyderabad', 'Adilabad'], 'puducherry': ['Yanam', 'Mahe', 'Karaikal', 'Puducherry'], 'karnataka': ['Vijayapura', 'Mysuru', 'Mandya', 'Ramanagara', 'Tumakuru', 'Chamarajanagara', 'Kodagu', 'Bengaluru', 'Dakshina Kannada', 'Bengaluru Rural', 'Kolar', 'Hassan', 'Chikkaballapura', 'Chikkamagaluru', 'Udupi', 'Shivamogga', 'Davanagere', 'Chitradurga', 'Haveri', 'Uttara Kannada', 'Dharwad', 'Ballari', 'Gadag', 'Koppal', 'Raichur', 'Bagalkote', 'Yadgir', 'Belagavi', 'Kalaburagi', 'Bidar'], 'chandigarh': ['Chandigarh'], 'himachal pradesh': ['Bilaspur', 'Hamirpur', 'Sirmaur', 'Solan', 'Shimla', 'Una', 'Kinnaur', 'Mandi', 'Kullu', 'Kangra', 'Chamba', 'Lahul & Spiti'], 'rajasthan': ['Pratapgarh', 'Bikaner', 'Hanumangarh', 'Ganganagar', 'Chittaurgarh', 'Rajsamand', 'Ajmer', 'Banswara', 'Dungarpur', 'Jhalawar', 'Udaipur', 'Baran', 'Sirohi', 'Kota', 'Bundi', 'Jalor', 'Bhilwara', 'Pali', 'Tonk', 'Sawai Madhopur', 'Barmer', 'Dhaulpur', 'Karauli', 'Dausa', 'Nagaur', 'Bharatpur', 'Jodhpur', 'Jaipur', 'Alwar', 'Sikar', 'Jaisalmer', 'Jhunjhunu', 'Churu'], 'mizoram': ['Lawngtlai', 'Saiha', 'Lunglei', 'Serchhip', 'Champhai', 'Mamit', 'Aizawl', 'Kolasib'], 'chattisgarh': ['Balrampur', 'Surguja', 'Surajpur', 'Korba', 'Jashpur', 'Koriya', 'Sukma', 'Bilaspur', 'Raigarh', 'Bijapur', 'Mungeli', 'Baloda Bazar', 'Rajnandgaon', 'Bametara', 'Janjgir - Champa', 'Kabeerdham', 'Balod', 'Dhamtari', 'Durg', 'Raipur', 'Gariaband', 'Kondagaon', 'Bastar', 'Dakshin Bastar Dantewada', 'Narayanpur', 'Uttar Bastar Kanker', 'Mahasamund'], 'odisha': ['Sambalpur', 'Debagarh', 'Bargarh', 'Jharsuguda', 'Baleshwar', 'Kendujhar', 'Sundargarh', 'Mayurbhanj', 'Gajapati', 'Ganjam', 'Kendrapara', 'Anugul', 'Malkangiri', 'Koraput', 'Rayagada', 'Nabarangapur', 'Puri', 'Jagatsinghapur', 'Kalahandi', 'Khordha', 'Nayagarh', 'Kandhamal', 'Cuttack', 'Baudh', 'Balangir', 'Nuapada', 'Subarnapur', 'Jajapur', 'Dhenkanal', 'Bhadrak'], 'kerala': ['Kannur', 'Thiruvananthapuram', 'Kollam', 'Pathanamthitta', 'Kottayam', 'Alappuzha', 'Ernakulam', 'Idukki', 'Thrissur', 'Palakkad', 'Malappuram', 'Kozhikode', 'Wayanad', 'Kasaragod'], 'ladakh': ['Kargil', 'Leh'], 'tamil nadu': ['Ramanathapuram', 'Sivaganga', 'Pudukkottai', 'Nagapattinam', 'Cuddalore', 'Viluppuram', 'Kanniyakumari', 'Thoothukkudi', 'Tirunelveli', 'Virudhunagar', 'Theni', 'Madurai', 'Dindigul', 'Thiruvarur', 'Karur', 'Thanjavur', 'Tiruppur', 'Ariyalur', 'Tiruchirappalli', 'Coimbatore', 'Perambalur', 'Namakkal', 'The Nilgiris', 'Erode', 'Salem', 'Dharmapuri', 'Tiruvannamalai', 'Krishnagiri', 'Kancheepuram', 'Chennai', 'Vellore', 'Thiruvallur'], 'nagaland': ['Dimapur', 'Kohima', 'Phek', 'Zunheboto', 'Wokha', 'Peren', 'Kiphire', 'Tuensang', 'Mokokchung', 'Longleng', 'Mon'], 'madhya pradesh': ['Niwari', 'Panna', 'Chhatarpur', 'Datia', 'Agar Malwa', 'Hoshangabad', 'Mandla', 'Indore', 'Dhar', 'Narsimhapur', 'Dindori', 'Jhabua', 'Anuppur', 'Dewas', 'Jabalpur', 'Sehore', 'Raisen', 'Ujjain', 'Bhopal', 'Ratlam', 'Umaria', 'Katni', 'Shahdol', 'Rajgarh', 'Vidisha', 'Shajapur', 'Damoh', 'Sagar', 'Sidhi', 'Singrauli', 'Mandsaur', 'Ashoknagar', 'Guna', 'Satna', 'Rewa', 'Neemuch', 'Tikamgarh', 'Shivpuri', 'Sheopur', 'Gwalior', 'Bhind', 'Morena', 'Betul', 'Barwani', 'Balaghat', 'East Nimar', 'West Nimar', 'Harda', 'Chhindwara', 'Alirajpur', 'Seoni', 'Burhanpur'], 'goa': ['South Goa', 'North Goa'], 'sikkim': ['East District', 'South District', 'West District', 'North District'], 'bihar': ['Aurangabad', 'Kishanganj', 'Purnia', 'Madhubani', 'Supaul', 'Araria', 'Madhepura', 'Muzaffarpur', 'Siwan', 'Saran', 'Patna', 'Nalanda', 'Jehanabad', 'Arwal', 'Sheikhpura', 'Lakhisarai', 'Bhagalpur', 'Begusarai', 'Vaishali', 'Munger', 'Gaya', 'Nawada', 'Banka', 'Jamui', 'Rohtas', 'Kaimur (bhabua)', 'Saharsa', 'Darbhanga', 'Buxar', 'Bhojpur', 'Khagaria', 'Katihar', 'Samastipur', 'Gopalganj', 'Sheohar', 'Sitamarhi', 'Purba Champaran', 'Pashchim Champaran'], 'andhra pradesh': ['Chittoor', 'Y.S.R.', 'West Godavari', 'S.P.S. Nellore', 'Anantapur', 'Kurnool', 'Prakasam', 'East Godavari', 'Guntur', 'Krishna', 'Visakhapatnam', 'Vizianagaram', 'Srikakulam'], 'jharkhand': ['Hazaribagh', 'Kodarma', 'Simdega', 'Pashchimi Singhbhum', 'Purbi Singhbhum', 'Saraikela-kharsawan', 'Khunti', 'Gumla', 'Lohardaga', 'Ranchi', 'Ramgarh', 'Bokaro', 'Latehar', 'Dhanbad', 'Jamtara', 'Garhwa', 'Chatra', 'Palamu', 'Deoghar', 'Dumka', 'Giridih', 'Pakur', 'Godda', 'Sahibganj'], 'meghalaya': ['South West Garo Hills', 'North Garo Hills', 'South West Khasi Hills', 'West Jaintia Hills', 'East Garo Hills', 'West Garo Hills', 'South Garo Hills', 'East Khasi Hills', 'East Jaintia Hills', 'West Khasi Hills', 'Ribhoi'], 'delhi': ['North West Delhi', 'South East Delhi', 'Shahdara', 'South Delhi', 'New Delhi', 'Central Delhi', 'South West Delhi', 'East Delhi', 'West Delhi', 'North East Delhi', 'North Delhi'], 'west bengal': ['Uttar Dinajpur', 'Cooch Behar', 'Kalimpong', 'Paschim Bardhaman', 'Alipurduar', 'Kolkata', 'Howrah', 'Hooghly', 'North 24 Parganas', 'Bankura', 'Puruliya', 'Purba Bardhaman', 'Nadia', 'Birbhum', 'Murshidabad', 'Maldah', 'Dakshin Dinajpur', 'Jalpaiguri', 'Darjeeling', 'Jhargram', 'Purba Medinipur', 'Medinipur West', 'South 24 Parganas'], 'assam': ['West Karbi Anglong', 'Karbi Anglong', 'South Salmara Mancachar', 'Hojai', 'Biswanath', 'Majuli', 'Charaideo', 'Hailakandi', 'Karimganj', 'Cachar', 'Dima Hasao', 'Goalpara', 'Kamrup Metropolitan', 'Dhubri', 'Bongaigaon', 'Kamrup', 'Morigaon', 'Nalbari', 'Barpeta', 'Darrang', 'Kokrajhar', 'Nagaon', 'Baksa', 'Chirang', 'Udalguri', 'Golaghat', 'Sonitpur', 'Jorhat', 'Sivasagar', 'Lakhimpur', 'Dibrugarh', 'Dhemaji', 'Tinsukia'], 'lakshadweep': ['Lakshadweep'], 'andaman and nicobar islands': ['Nicobars', 'South Andaman', 'North & Middle Andaman'], 'arunachal pradesh': ['Kamle', 'Lepa Rada', 'West Siang', 'Pakke Kessang', 'Shi Yomi', 'Siang', 'Lower Dibang Valley', 'Upper Dibang Valley', 'Lower Siang', 'Upper Siang', 'Longding', 'Namsai', 'Kra Daadi', 'West Kamenghttps://github.com/covid19india/CovidCrowd/issues/6', 'East Kameng', 'Lower Subansiri', 'Kurung Kumey', 'Lohit', 'East Siang', 'Tirap', 'Papum Pare', 'Tawang', 'Changlang', 'Anjaw', 'Upper Subansiri'], 'dadar and nagar haveli': ['Dadra & Nagar Haveli'], 'jammu and kashmir': ['Mirpur', 'Muzaffarabad', 'Samba', 'Udhampur', 'Kathua', 'Jammu', 'Doda', 'Reasi', 'Ramban', 'Rajouri', 'Kulgam', 'Shupiyan', 'Punch', 'Pulwama', 'Badgam', 'Srinagar', 'Kishtwar', 'Anantnag', 'Ganderbal', 'Baramula', 'Bandipore', 'Kupwara'], 'haryana': ['Ambala', 'Panchkula', 'Rohtak', 'Bhiwani', 'Sonipat', 'Panipat', 'Hisar', 'Fatehabad', 'Jind', 'Karnal', 'Sirsa', 'Kaithal', 'Kurukshetra', 'Yamunanagar', 'Charki Dadri', 'Palwal', 'Nuh', 'Rewari', 'Mahendragarh', 'Faridabad', 'Gurugram', 'Jhajjar'], 'daman and diu': ['Diu', 'Daman'], 'uttarakhand': ['Udham Singh Nagar', 'Champawat', 'Nainital', 'Almora', 'Garhwal', 'Hardwar', 'Bageshwar', 'Pithoragarh', 'Rudraprayag', 'Tehri Garhwal', 'Dehradun', 'Chamoli', 'Uttarkashi'], 'punjab': ['Kapurthala', 'Pathankot', 'Firozpur', 'Mansa', 'Patiala', 'Bathinda', 'Barnala', 'Sangrur', 'Sri Muktsar Sahib', 'Fatehgarh Sahib', 'Faridkot', 'S.A.S. Nagar', 'Ludhiana', 'Moga', 'Fazilka', 'Shahid Bhagat Singh Nagar', 'Rupnagar', 'Tarn Taran', 'Jalandhar', 'Amritsar', 'Hoshiarpur', 'Gurdaspur'], 'uttar pradesh': ['Pratapgarh', 'Hamirpur', 'Balrampur', 'Shamli', 'Rampur', 'Moradabad', 'Meerut', 'Baghpat', 'Muzaffarnagar', 'Bijnor', 'Saharanpur', 'Mahoba', 'Sambhal', 'Ghaziabad', 'Amethi', 'Sonbhadra', 'Lalitpur', 'Mirzapur', 'Bhadohi', 'Chandauli', 'Chitrakoot', 'Varanasi', 'Prayagraj', 'Kaushambi', 'Ghazipur', 'Banda', 'Jhansi', 'Jaunpur', 'Ballia', 'Fatehpur', 'Mau', 'Azamgarh', 'Jalaun', 'Rae Bareli', 'Ambedkar Nagar', 'Sultanpur', 'Deoria', 'Kanpur Dehat', 'Faizabad', 'Auraiya', 'Kanpur Nagar', 'Etawah', 'Unnao', 'Sant Kabir Nagar', 'Gorakhpur', 'Basti', 'Lucknow', 'Kannauj', 'Kushinagar', 'Bara Banki', 'Gonda', 'Agra', 'Mahrajganj', 'Mainpuri', 'Siddharthnagar', 'Firozabad', 'Farrukhabad', 'Hardoi', 'Etah', 'Hathras', 'Sitapur', 'Shrawasti', 'Mathura', 'Kasganj', 'Aligarh', 'Shahjahanpur', 'Bahraich', 'Budaun', 'Kheri', 'Gautam Buddha Nagar', 'Bulandshahr', 'Pilibhit', 'Bareilly', 'Hapur', 'Amroha'], 'gujarat': ['Morbi', 'Anand', 'Kheda', 'Surendranagar', 'Kachchh', 'Sabar Kantha', 'Mahisagar', 'Aravalli', 'Dohad', 'Panch Mahals', 'Ahmadabad', 'Gandhinagar', 'Mahesana', 'Patan', 'Banas Kantha', 'Navsari', 'Devbhumi Dwarka', 'Jamnagar', 'Junagadh', 'Bhavnagar', 'Rajkot', 'Gir Somnath', 'Chota Udaipur', 'Botad', 'Tapi', 'Surat', 'Narmada', 'Porbandar', 'Bharuch', 'Vadodara', 'The Dangs', 'Amreli', 'Valsad'], 'maharashtra': ['Mumbai Suburban', 'Raigarh', 'Aurangabad', 'Nagpur', 'Dhule', 'Amravati', 'Nandurbar', 'Palghar', 'Thane', 'Sindhudurg', 'Kolhapur', 'Sangli', 'Ratnagiri', 'Satara', 'Solapur', 'Osmanabad', 'Latur', 'Mumbai', 'Bid', 'Pune', 'Parbhani', 'Nanded', 'Hingoli', 'Ahmadnagar', 'Jalna', 'Yavatmal', 'Chandrapur', 'Washim', 'Gadchiroli', 'Nashik', 'Akola', 'Buldana', 'Wardha', 'Jalgaon', 'Bhandara', 'Gondiya'], 'tripura': ['Unokoti', 'South Tripura', 'West Tripura', 'Khowai', 'Gomati', 'Sipahijala', 'Dhalai', 'North Tripura'], 'manipur': ['Pherzawl', 'Noney', 'Ukhrul', 'Tengnoupal', 'Thoubal', 'Kangpokpi', 'Jiribam', 'Imphal East', 'Churachandpur', 'Chandel', 'Bishnupur', 'Kakching', 'Imphal West', 'Tamenglong', 'Senapati', 'Kamjong']}


class PatientStatus:
    HOSPITALISED = "Hospitalized"
    RECOVERED = "Recovered"
    DECEASED = "Deceased"
    HOME_QUARANTINED = "Home Quarantined"

    CHOICES = [HOSPITALISED, RECOVERED, DECEASED, HOME_QUARANTINED]


class Gender:
    MALE = "Male"
    FEMALE = "Female"
    OTHERS = "Others"
    UNKNOWN = "Unknown"

    CHOICES = [MALE, FEMALE, OTHERS, UNKNOWN]
