# Generated by Django 3.0.4 on 2020-03-19 03:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("onset_date", models.DateField()),
                ("diagnosed_date", models.DateField()),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                (
                    "detected_location",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                (
                    "current_location",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("R", "Recovered"),
                            ("H", "Hospitalized"),
                            ("D", "Deceased"),
                        ],
                        max_length=1,
                    ),
                ),
                ("travel_mode", models.TextField()),
                ("notes", models.TextField()),
                (
                    "contacts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="_patient_contacts_+",
                        to="patients.Patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("url", models.URLField()),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.Patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("onset_date", models.DateField()),
                ("diagnosed_date", models.DateField()),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("detected_location", models.CharField(max_length=150)),
                ("current_location", models.CharField(max_length=150)),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("R", "Recovered"),
                            ("H", "Hospitalized"),
                            ("D", "Deceased"),
                        ],
                        max_length=1,
                    ),
                ),
                ("travel_mode", models.CharField(max_length=150)),
                ("source", models.TextField()),
                ("notes", models.TextField()),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="patients.Report",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="patient",
            name="report",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="patients.Report",
            ),
        ),
    ]
