# Generated by Django 3.0.4 on 2020-03-20 05:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("onset_date", models.DateField()),
                ("diagnosed_date", models.DateField()),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("detected_location", models.CharField(max_length=150)),
                ("current_location", models.CharField(max_length=150)),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("R", "Recovered"),
                            ("H", "Hospitalized"),
                            ("D", "Deceased"),
                        ],
                        max_length=1,
                    ),
                ),
                ("travel_mode", models.CharField(max_length=150)),
                ("source", models.TextField()),
                ("notes", models.TextField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            (
                                "Andaman and Nicobar Islands",
                                "Andaman and Nicobar Islands",
                            ),
                            ("Andhra Pradesh", "Andhra Pradesh"),
                            ("Assam", "Assam"),
                            ("Bihar", "Bihar"),
                            ("Chandigarh", "Chandigarh"),
                            ("Chattisgarh", "Chattisgarh"),
                            ("Dadar and Nagar Haveli", "Dadar and Nagar Haveli"),
                            ("Daman and Diu", "Daman and Diu"),
                            ("Goa", "Goa"),
                            ("Gujarat", "Gujarat"),
                            ("Haryana", "Haryana"),
                            ("Himachal Pradesh", "Himachal Pradesh"),
                            ("Jammu and Kashmir", "Jammu and Kashmir"),
                            ("Jharkhand", "Jharkand"),
                            ("Karnataka", "Karnataka"),
                            ("Kerala", "Kerala"),
                            ("Ladakh", "Ladakh"),
                            ("Lakshadweep", "Lakshadweep"),
                            ("Madhya Pradesh", "Madhya Pradesh"),
                            ("Maharastra", "Maharastra"),
                            ("Manipur", "Manipur"),
                            ("Meghalaya", "Meghalaya"),
                            ("Mizoram", "Mizoram"),
                            ("Nagaland", "Nagaland"),
                            ("NCT of Delhi", "NCT of Delhi"),
                            ("Odisha", "Odisha"),
                            ("Puducherry", "Puducherry"),
                            ("Punjab", "Punjab"),
                            ("Rajasthan", "Rajasthan"),
                            ("Sikkim", "Sikkim"),
                            ("Tamil Nadu", "Tamil Nadu"),
                            ("Telengana", "Telengana"),
                            ("Tripura", "Tripura"),
                            ("Uttar Pradesh", "Uttar Pradesh"),
                            ("Uttarakhand", "Uttarakhand"),
                            ("West Bengal", "West Bengal"),
                        ],
                        max_length=150,
                        null=True,
                    ),
                ),
                ("reported_time", models.DateTimeField(auto_now_add=True)),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="patients.Report",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("onset_date", models.DateField()),
                ("diagnosed_date", models.DateField()),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("detected_location", models.CharField(max_length=150)),
                ("current_location", models.CharField(max_length=150)),
                (
                    "detected_location_pt",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                (
                    "current_location_pt",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("R", "Recovered"),
                            ("H", "Hospitalized"),
                            ("D", "Deceased"),
                        ],
                        max_length=1,
                    ),
                ),
                ("travel_mode", models.TextField()),
                ("notes", models.TextField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            (
                                "Andaman and Nicobar Islands",
                                "Andaman and Nicobar Islands",
                            ),
                            ("Andhra Pradesh", "Andhra Pradesh"),
                            ("Assam", "Assam"),
                            ("Bihar", "Bihar"),
                            ("Chandigarh", "Chandigarh"),
                            ("Chattisgarh", "Chattisgarh"),
                            ("Dadar and Nagar Haveli", "Dadar and Nagar Haveli"),
                            ("Daman and Diu", "Daman and Diu"),
                            ("Goa", "Goa"),
                            ("Gujarat", "Gujarat"),
                            ("Haryana", "Haryana"),
                            ("Himachal Pradesh", "Himachal Pradesh"),
                            ("Jammu and Kashmir", "Jammu and Kashmir"),
                            ("Jharkhand", "Jharkand"),
                            ("Karnataka", "Karnataka"),
                            ("Kerala", "Kerala"),
                            ("Ladakh", "Ladakh"),
                            ("Lakshadweep", "Lakshadweep"),
                            ("Madhya Pradesh", "Madhya Pradesh"),
                            ("Maharastra", "Maharastra"),
                            ("Manipur", "Manipur"),
                            ("Meghalaya", "Meghalaya"),
                            ("Mizoram", "Mizoram"),
                            ("Nagaland", "Nagaland"),
                            ("NCT of Delhi", "NCT of Delhi"),
                            ("Odisha", "Odisha"),
                            ("Puducherry", "Puducherry"),
                            ("Punjab", "Punjab"),
                            ("Rajasthan", "Rajasthan"),
                            ("Sikkim", "Sikkim"),
                            ("Tamil Nadu", "Tamil Nadu"),
                            ("Telengana", "Telengana"),
                            ("Tripura", "Tripura"),
                            ("Uttar Pradesh", "Uttar Pradesh"),
                            ("Uttarakhand", "Uttarakhand"),
                            ("West Bengal", "West Bengal"),
                        ],
                        max_length=150,
                        null=True,
                    ),
                ),
                ("district", models.CharField(max_length=150, null=True)),
                ("source", models.TextField()),
                (
                    "contacts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="_patient_contacts_+",
                        to="patients.Patient",
                    ),
                ),
                (
                    "report",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="patients.Report",
                    ),
                ),
            ],
        ),
    ]
