# Generated by Django 3.0.4 on 2020-03-19 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20200319_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reported_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
