# Generated by Django 3.0.4 on 2020-03-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("patients", "0004_report_patient_id"),
        ("patients", "0005_auto_20200321_1131"),
    ]

    dependencies = [
        ("patients", "0003_auto_20200321_0943"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="patient_id",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="government_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
