# Generated by Django 3.0.4 on 2020-03-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20200321_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='current_status',
            field=models.CharField(choices=[('Hospitalized', 'Hospitalized'), ('Recovered', 'Recovered'), ('Deceased', 'Deceased'), ('Home Quarantined', 'Home Quarantined')], max_length=25),
        ),
        migrations.AlterField(
            model_name='report',
            name='current_status',
            field=models.CharField(choices=[('Hospitalized', 'Hospitalized'), ('Recovered', 'Recovered'), ('Deceased', 'Deceased'), ('Home Quarantined', 'Home Quarantined')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='statusupdate',
            name='patient_status',
            field=models.CharField(choices=[('Hospitalized', 'Hospitalized'), ('Recovered', 'Recovered'), ('Deceased', 'Deceased'), ('Home Quarantined', 'Home Quarantined')], max_length=25),
        ),
    ]
