# Generated by Django 3.0.4 on 2020-03-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_auto_20200322_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorreport',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('U', 'Used'), ('D', 'Discarded')], default='N', max_length=1),
        ),
    ]
