# Generated by Django 3.0.4 on 2020-03-22 23:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_auto_20200323_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthistory',
            name='place_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='travel_mode',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='type',
            field=models.CharField(choices=[('placeVisit', 'placeVisit'), ('travel', 'travel')], max_length=15, null=True),
        ),
    ]
